# -*- coding: utf-8 -*-
"""찾아보기 생성에 쓰는 대조표 — 발행처 표기명 · 자료 종류 · 약어"""

# 도메인 → (표기명, 자료 종류)
PUB = {
    "webstore.iec.ch":        ("IEC (국제전기기술위원회)", "표준"),
    "standards.ieee.org":     ("IEEE", "표준"),
    "standards.iteh.ai":      ("iTeh Standards", "표준"),
    "cdn.standards.iteh.ai":  ("iTeh Standards", "표준"),
    "standards.globalspec.com": ("GlobalSpec", "표준"),
    "webstore.ansi.org":      ("ANSI", "표준"),
    "bipm.org":               ("BIPM (국제도량형국)", "표준"),
    "oiml.org":               ("OIML (국제법정계량기구)", "표준"),
    "io-link.com":            ("IO-Link Community", "표준"),
    "nist.gov":               ("NIST 미국 국립표준기술연구소", "표준"),
    "opcfoundation.org":      ("OPC Foundation", "표준"),
    "plcopen.org":            ("PLCopen", "표준"),
    "odva.org":               ("ODVA", "표준"),

    "sick.com":               ("SICK", "제조사"),
    "siemens.com":            ("Siemens", "제조사"),
    "festo.com":              ("FESTO", "제조사"),
    "balluff.com":            ("Balluff", "제조사"),
    "ifm.com":                ("ifm", "제조사"),
    "bannerengineering.com":  ("Banner Engineering", "제조사"),
    "boschrexroth.com":       ("Bosch Rexroth", "제조사"),
    "idskr.panasonic.com":    ("Panasonic", "제조사"),
    "kr.misumi-ec.com":       ("OMRON (한국미스미 배포)", "제조사"),
    "kr.mitsubishielectric.com": ("미쓰비시전기", "제조사"),
    "motoman.com":            ("야스카와 모토맨", "제조사"),
    "yaskawa-global.com":     ("야스카와", "제조사"),
    "neuromeka.com":          ("뉴로메카", "제조사"),
    "santest.co.jp":          ("SANTEST", "제조사"),
    "se.com":                 ("Schneider Electric", "제조사"),
    "xnergytech.com":         ("Xnergy", "제조사"),

    "mdpi.com":               ("MDPI", "학술"),
    "pmc.ncbi.nlm.nih.gov":   ("PMC (미국 국립의학도서관)", "학술"),
    "arxiv.org":              ("arXiv", "학술"),

    "en.wikipedia.org":       ("Wikipedia", "해설"),
    "forum.digikey.com":      ("DigiKey", "해설"),
    "industryx.ai":           ("IndustryX", "해설"),
    "scadaprotocols.com":     ("SCADA Protocols", "해설"),
}

CAT_ORDER = ["표준", "제조사", "학술", "해설"]
CAT_DESC = {
    "표준": ("국제 표준 · 규격 단체", "규격 원문과 공식 해설이다. 이 책의 정의와 수치가 어디에 근거하는지 확인할 때 본다."),
    "제조사": ("제조사 기술자료", "실물 사양과 기술 해설이다. 형상 확인과 사양서 읽기에 쓴다."),
    "학술": ("학술 논문 · 공개 자료", "원리를 더 깊이 보려는 독자를 위한 자료다. 무료로 볼 수 있는 것만 실었다."),
    "해설": ("웹 해설 자료", "표준 문서보다 읽기 쉬운 설명이다. 개념을 처음 잡을 때 본다."),
}

# 약어 → (정식 명칭, 우리말 풀이)
ABBR = [
    ("A/D", "Analog to Digital", "아날로그 신호를 디지털 숫자로 바꾸는 변환"),
    ("AGV", "Automated Guided Vehicle", "정해진 경로를 따라 움직이는 무인 반송차"),
    ("AMR", "Autonomous Mobile Robot", "경로를 스스로 정하는 자율주행 반송 로봇"),
    ("CCD / CMOS", "Charge-Coupled Device / Complementary Metal-Oxide-Semiconductor", "빛을 전기신호로 바꾸는 두 가지 이미지 소자 방식"),
    ("CPU", "Central Processing Unit", "제어기의 연산을 담당하는 중앙처리장치"),
    ("DSP", "Digital Signal Processing", "디지털 신호 처리"),
    ("EEPROM", "Electrically Erasable Programmable Read-Only Memory", "전원이 꺼져도 내용이 남는 비휘발성 메모리"),
    ("EMC / EMI", "Electromagnetic Compatibility / Interference", "전자파 적합성 · 전자파 장해"),
    ("ESPE", "Electro-Sensitive Protective Equipment", "사람의 진입을 감지해 기계를 멈추는 안전 장치"),
    ("HSR", "High-availability Seamless Redundancy", "무중단 이중화 방식 (IEC 62439-3)"),
    ("IIoT", "Industrial Internet of Things", "산업용 사물인터넷"),
    ("ISDU", "Indexed Service Data Unit", "IO-Link의 서비스 데이터 전송 단위"),
    ("IT / OT", "Information Technology / Operational Technology", "정보 기술 · 운영 기술"),
    ("LOTO", "Lock Out / Tag Out", "정비 중 기동을 막는 전원 차단·잠금 절차"),
    ("MCU", "Micro Controller Unit", "센서 안에 들어가는 작은 연산 장치"),
    ("MES", "Manufacturing Execution System", "생산 실행 시스템"),
    ("MQTT", "Message Queuing Telemetry Transport", "가벼운 발행/구독 메시지 규격 (ISO/IEC 20922)"),
    ("MRM", "Media Redundancy Manager", "MRP 링에서 경로를 관리하는 장치"),
    ("MRP", "Media Redundancy Protocol", "산업용 링 이중화 규격 (IEC 62439-2)"),
    ("MS / NS", "Module Status / Network Status", "EtherNet/IP 기기의 상태 표시등"),
    ("NPN / PNP", "Negative-Positive-Negative / Positive-Negative-Positive", "센서 출력 트랜지스터의 두 가지 결선 방식"),
    ("OPC UA", "Open Platform Communications Unified Architecture", "값에 의미를 붙여 전달하는 산업 통신 표준 (IEC 62541)"),
    ("PID", "Proportional-Integral-Derivative", "비례·적분·미분을 조합한 제어 방식"),
    ("PL", "Performance Level", "안전 기능의 성능 수준 (ISO 13849-1)"),
    ("PLC", "Programmable Logic Controller", "현장 설비를 제어하는 산업용 제어기"),
    ("PRP", "Parallel Redundancy Protocol", "두 경로로 동시에 보내는 무중단 이중화 (IEC 62439-3)"),
    ("PSD", "Position Sensitive Device", "빛이 닿은 위치를 읽는 광학 소자"),
    ("RSTP", "Rapid Spanning Tree Protocol", "일반 이더넷의 경로 이중화 규격"),
    ("SDCI", "Single-drop Digital Communication Interface", "IO-Link의 국제 표준상 명칭 (IEC 61131-9)"),
    ("SIO", "Standard Input/Output", "IO-Link 기기가 통신 없이 ON/OFF만 내보내는 모드"),
    ("SMPS", "Switching Mode Power Supply", "스위칭 방식 직류 전원 장치"),
    ("SPOF", "Single Point of Failure", "혼자 죽으면 전체가 멈추는 단일 장애점"),
    ("STO", "Safe Torque Off", "안전 회로 동작 시 모터 토크를 끊는 안전 기능"),
    ("TEDS", "Transducer Electronic Data Sheet", "센서가 스스로 갖고 다니는 전자 사양서 (IEEE 1451)"),
    ("TOF", "Time of Flight", "신호가 왕복한 시간으로 거리를 재는 방식"),
    ("UPS", "Uninterruptible Power Supply", "정전 시에도 전원을 유지하는 무정전 전원 장치"),
    ("VIM", "International Vocabulary of Metrology", "국제 계량 용어집 (JCGM 200)"),
    ("VLAN", "Virtual Local Area Network", "물리 배선을 공유하면서 논리적으로 나눈 망"),
    ("%FS", "Percent of Full Scale", "측정 범위 전체 대비 백분율"),
]
